<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

/**
 * 컨사이니 일괄 업로드 deep-interview (2026-05-28) — Q5 결정.
 *
 * ISO 3166-1 alpha-3 코드 + 외교부/위키 한국어명 + 주요 통화(ISO 4217).
 * 기존 ProductionSeeder::seedCountries() 의 8개 (일본·몽골·미얀마·카자흐스탄·
 * 중국·UAE·러시아·한국)는 같은 code 로 upsert 되어 통합 (UAE → 아랍에미리트로 표기 정규화).
 *
 * 컨사이니 엑셀 일괄 업로드 시 country lookup 안정성 확보. 신규 SaaS 고객 추가될 때마다
 * country 시드 보강할 일 거의 없게 1회 완비.
 *
 * 신규 row 추가 시 code (alpha-3) 기준 정렬 유지 권장. 코소보(XKX)는 ISO 미등재
 * 임시 코드이나 EU 실무에서 통용.
 */
class CountrySeeder extends Seeder
{
    public function run(): void
    {
        foreach (self::countries() as $c) {
            Country::updateOrCreate(['code' => $c['code']], $c);
        }
    }

    /** @return array<int, array{name: string, code: string, currency: string}> */
    public static function countries(): array
    {
        return [
            // ===== Africa =====
            ['name' => '알제리',                'code' => 'DZA', 'currency' => 'DZD'],
            ['name' => '앙골라',                'code' => 'AGO', 'currency' => 'AOA'],
            ['name' => '베냉',                  'code' => 'BEN', 'currency' => 'XOF'],
            ['name' => '보츠와나',              'code' => 'BWA', 'currency' => 'BWP'],
            ['name' => '부르키나파소',          'code' => 'BFA', 'currency' => 'XOF'],
            ['name' => '부룬디',                'code' => 'BDI', 'currency' => 'BIF'],
            ['name' => '카메룬',                'code' => 'CMR', 'currency' => 'XAF'],
            ['name' => '카보베르데',            'code' => 'CPV', 'currency' => 'CVE'],
            ['name' => '중앙아프리카공화국',    'code' => 'CAF', 'currency' => 'XAF'],
            ['name' => '차드',                  'code' => 'TCD', 'currency' => 'XAF'],
            ['name' => '코모로',                'code' => 'COM', 'currency' => 'KMF'],
            ['name' => '콩고공화국',            'code' => 'COG', 'currency' => 'XAF'],
            ['name' => '콩고민주공화국',        'code' => 'COD', 'currency' => 'CDF'],
            ['name' => '지부티',                'code' => 'DJI', 'currency' => 'DJF'],
            ['name' => '이집트',                'code' => 'EGY', 'currency' => 'EGP'],
            ['name' => '적도기니',              'code' => 'GNQ', 'currency' => 'XAF'],
            ['name' => '에리트레아',            'code' => 'ERI', 'currency' => 'ERN'],
            ['name' => '에스와티니',            'code' => 'SWZ', 'currency' => 'SZL'],
            ['name' => '에티오피아',            'code' => 'ETH', 'currency' => 'ETB'],
            ['name' => '가봉',                  'code' => 'GAB', 'currency' => 'XAF'],
            ['name' => '감비아',                'code' => 'GMB', 'currency' => 'GMD'],
            ['name' => '가나',                  'code' => 'GHA', 'currency' => 'GHS'],
            ['name' => '기니',                  'code' => 'GIN', 'currency' => 'GNF'],
            ['name' => '기니비사우',            'code' => 'GNB', 'currency' => 'XOF'],
            ['name' => '코트디부아르',          'code' => 'CIV', 'currency' => 'XOF'],
            ['name' => '케냐',                  'code' => 'KEN', 'currency' => 'KES'],
            ['name' => '레소토',                'code' => 'LSO', 'currency' => 'LSL'],
            ['name' => '라이베리아',            'code' => 'LBR', 'currency' => 'LRD'],
            ['name' => '리비아',                'code' => 'LBY', 'currency' => 'LYD'],
            ['name' => '마다가스카르',          'code' => 'MDG', 'currency' => 'MGA'],
            ['name' => '말라위',                'code' => 'MWI', 'currency' => 'MWK'],
            ['name' => '말리',                  'code' => 'MLI', 'currency' => 'XOF'],
            ['name' => '모리타니',              'code' => 'MRT', 'currency' => 'MRU'],
            ['name' => '모리셔스',              'code' => 'MUS', 'currency' => 'MUR'],
            ['name' => '모로코',                'code' => 'MAR', 'currency' => 'MAD'],
            ['name' => '모잠비크',              'code' => 'MOZ', 'currency' => 'MZN'],
            ['name' => '나미비아',              'code' => 'NAM', 'currency' => 'NAD'],
            ['name' => '니제르',                'code' => 'NER', 'currency' => 'XOF'],
            ['name' => '나이지리아',            'code' => 'NGA', 'currency' => 'NGN'],
            ['name' => '르완다',                'code' => 'RWA', 'currency' => 'RWF'],
            ['name' => '상투메 프린시페',       'code' => 'STP', 'currency' => 'STN'],
            ['name' => '세네갈',                'code' => 'SEN', 'currency' => 'XOF'],
            ['name' => '세이셸',                'code' => 'SYC', 'currency' => 'SCR'],
            ['name' => '시에라리온',            'code' => 'SLE', 'currency' => 'SLE'],
            ['name' => '소말리아',              'code' => 'SOM', 'currency' => 'SOS'],
            ['name' => '남아프리카공화국',      'code' => 'ZAF', 'currency' => 'ZAR'],
            ['name' => '남수단',                'code' => 'SSD', 'currency' => 'SSP'],
            ['name' => '수단',                  'code' => 'SDN', 'currency' => 'SDG'],
            ['name' => '탄자니아',              'code' => 'TZA', 'currency' => 'TZS'],
            ['name' => '토고',                  'code' => 'TGO', 'currency' => 'XOF'],
            ['name' => '튀니지',                'code' => 'TUN', 'currency' => 'TND'],
            ['name' => '우간다',                'code' => 'UGA', 'currency' => 'UGX'],
            ['name' => '잠비아',                'code' => 'ZMB', 'currency' => 'ZMW'],
            ['name' => '짐바브웨',              'code' => 'ZWE', 'currency' => 'ZWL'],

            // ===== Americas =====
            ['name' => '앤티가 바부다',         'code' => 'ATG', 'currency' => 'XCD'],
            ['name' => '아르헨티나',            'code' => 'ARG', 'currency' => 'ARS'],
            ['name' => '바하마',                'code' => 'BHS', 'currency' => 'BSD'],
            ['name' => '바베이도스',            'code' => 'BRB', 'currency' => 'BBD'],
            ['name' => '벨리즈',                'code' => 'BLZ', 'currency' => 'BZD'],
            ['name' => '볼리비아',              'code' => 'BOL', 'currency' => 'BOB'],
            ['name' => '브라질',                'code' => 'BRA', 'currency' => 'BRL'],
            ['name' => '캐나다',                'code' => 'CAN', 'currency' => 'CAD'],
            ['name' => '칠레',                  'code' => 'CHL', 'currency' => 'CLP'],
            ['name' => '콜롬비아',              'code' => 'COL', 'currency' => 'COP'],
            ['name' => '코스타리카',            'code' => 'CRI', 'currency' => 'CRC'],
            ['name' => '쿠바',                  'code' => 'CUB', 'currency' => 'CUP'],
            ['name' => '도미니카연방',          'code' => 'DMA', 'currency' => 'XCD'],
            ['name' => '도미니카공화국',        'code' => 'DOM', 'currency' => 'DOP'],
            ['name' => '에콰도르',              'code' => 'ECU', 'currency' => 'USD'],
            ['name' => '엘살바도르',            'code' => 'SLV', 'currency' => 'USD'],
            ['name' => '그레나다',              'code' => 'GRD', 'currency' => 'XCD'],
            ['name' => '과테말라',              'code' => 'GTM', 'currency' => 'GTQ'],
            ['name' => '가이아나',              'code' => 'GUY', 'currency' => 'GYD'],
            ['name' => '아이티',                'code' => 'HTI', 'currency' => 'HTG'],
            ['name' => '온두라스',              'code' => 'HND', 'currency' => 'HNL'],
            ['name' => '자메이카',              'code' => 'JAM', 'currency' => 'JMD'],
            ['name' => '멕시코',                'code' => 'MEX', 'currency' => 'MXN'],
            ['name' => '니카라과',              'code' => 'NIC', 'currency' => 'NIO'],
            ['name' => '파나마',                'code' => 'PAN', 'currency' => 'PAB'],
            ['name' => '파라과이',              'code' => 'PRY', 'currency' => 'PYG'],
            ['name' => '페루',                  'code' => 'PER', 'currency' => 'PEN'],
            ['name' => '세인트키츠 네비스',     'code' => 'KNA', 'currency' => 'XCD'],
            ['name' => '세인트루시아',          'code' => 'LCA', 'currency' => 'XCD'],
            ['name' => '세인트빈센트 그레나딘', 'code' => 'VCT', 'currency' => 'XCD'],
            ['name' => '수리남',                'code' => 'SUR', 'currency' => 'SRD'],
            ['name' => '트리니다드 토바고',     'code' => 'TTO', 'currency' => 'TTD'],
            ['name' => '미국',                  'code' => 'USA', 'currency' => 'USD'],
            ['name' => '우루과이',              'code' => 'URY', 'currency' => 'UYU'],
            ['name' => '베네수엘라',            'code' => 'VEN', 'currency' => 'VES'],

            // ===== Asia =====
            ['name' => '아프가니스탄',          'code' => 'AFG', 'currency' => 'AFN'],
            ['name' => '아르메니아',            'code' => 'ARM', 'currency' => 'AMD'],
            ['name' => '아제르바이잔',          'code' => 'AZE', 'currency' => 'AZN'],
            ['name' => '바레인',                'code' => 'BHR', 'currency' => 'BHD'],
            ['name' => '방글라데시',            'code' => 'BGD', 'currency' => 'BDT'],
            ['name' => '부탄',                  'code' => 'BTN', 'currency' => 'BTN'],
            ['name' => '브루나이',              'code' => 'BRN', 'currency' => 'BND'],
            ['name' => '캄보디아',              'code' => 'KHM', 'currency' => 'KHR'],
            ['name' => '중국',                  'code' => 'CHN', 'currency' => 'CNY'],
            ['name' => '키프로스',              'code' => 'CYP', 'currency' => 'EUR'],
            ['name' => '조지아',                'code' => 'GEO', 'currency' => 'GEL'],
            ['name' => '인도',                  'code' => 'IND', 'currency' => 'INR'],
            ['name' => '인도네시아',            'code' => 'IDN', 'currency' => 'IDR'],
            ['name' => '이란',                  'code' => 'IRN', 'currency' => 'IRR'],
            ['name' => '이라크',                'code' => 'IRQ', 'currency' => 'IQD'],
            ['name' => '이스라엘',              'code' => 'ISR', 'currency' => 'ILS'],
            ['name' => '일본',                  'code' => 'JPN', 'currency' => 'JPY'],
            ['name' => '요르단',                'code' => 'JOR', 'currency' => 'JOD'],
            ['name' => '카자흐스탄',            'code' => 'KAZ', 'currency' => 'KZT'],
            ['name' => '쿠웨이트',              'code' => 'KWT', 'currency' => 'KWD'],
            ['name' => '키르기스스탄',          'code' => 'KGZ', 'currency' => 'KGS'],
            ['name' => '라오스',                'code' => 'LAO', 'currency' => 'LAK'],
            ['name' => '레바논',                'code' => 'LBN', 'currency' => 'LBP'],
            ['name' => '말레이시아',            'code' => 'MYS', 'currency' => 'MYR'],
            ['name' => '몰디브',                'code' => 'MDV', 'currency' => 'MVR'],
            ['name' => '몽골',                  'code' => 'MNG', 'currency' => 'MNT'],
            ['name' => '미얀마',                'code' => 'MMR', 'currency' => 'MMK'],
            ['name' => '네팔',                  'code' => 'NPL', 'currency' => 'NPR'],
            ['name' => '북한',                  'code' => 'PRK', 'currency' => 'KPW'],
            ['name' => '오만',                  'code' => 'OMN', 'currency' => 'OMR'],
            ['name' => '파키스탄',              'code' => 'PAK', 'currency' => 'PKR'],
            ['name' => '팔레스타인',            'code' => 'PSE', 'currency' => 'ILS'],
            ['name' => '필리핀',                'code' => 'PHL', 'currency' => 'PHP'],
            ['name' => '카타르',                'code' => 'QAT', 'currency' => 'QAR'],
            ['name' => '사우디아라비아',        'code' => 'SAU', 'currency' => 'SAR'],
            ['name' => '싱가포르',              'code' => 'SGP', 'currency' => 'SGD'],
            ['name' => '대한민국',              'code' => 'KOR', 'currency' => 'KRW'],
            ['name' => '스리랑카',              'code' => 'LKA', 'currency' => 'LKR'],
            ['name' => '시리아',                'code' => 'SYR', 'currency' => 'SYP'],
            ['name' => '대만',                  'code' => 'TWN', 'currency' => 'TWD'],
            ['name' => '타지키스탄',            'code' => 'TJK', 'currency' => 'TJS'],
            ['name' => '태국',                  'code' => 'THA', 'currency' => 'THB'],
            ['name' => '동티모르',              'code' => 'TLS', 'currency' => 'USD'],
            ['name' => '튀르키예',              'code' => 'TUR', 'currency' => 'TRY'],
            ['name' => '투르크메니스탄',        'code' => 'TKM', 'currency' => 'TMT'],
            ['name' => '아랍에미리트',          'code' => 'ARE', 'currency' => 'AED'],
            ['name' => '우즈베키스탄',          'code' => 'UZB', 'currency' => 'UZS'],
            ['name' => '베트남',                'code' => 'VNM', 'currency' => 'VND'],
            ['name' => '예멘',                  'code' => 'YEM', 'currency' => 'YER'],
            ['name' => '홍콩',                  'code' => 'HKG', 'currency' => 'HKD'],
            ['name' => '마카오',                'code' => 'MAC', 'currency' => 'MOP'],

            // ===== Europe =====
            ['name' => '알바니아',              'code' => 'ALB', 'currency' => 'ALL'],
            ['name' => '안도라',                'code' => 'AND', 'currency' => 'EUR'],
            ['name' => '오스트리아',            'code' => 'AUT', 'currency' => 'EUR'],
            ['name' => '벨라루스',              'code' => 'BLR', 'currency' => 'BYN'],
            ['name' => '벨기에',                'code' => 'BEL', 'currency' => 'EUR'],
            ['name' => '보스니아 헤르체고비나', 'code' => 'BIH', 'currency' => 'BAM'],
            ['name' => '불가리아',              'code' => 'BGR', 'currency' => 'BGN'],
            ['name' => '크로아티아',            'code' => 'HRV', 'currency' => 'EUR'],
            ['name' => '체코',                  'code' => 'CZE', 'currency' => 'CZK'],
            ['name' => '덴마크',                'code' => 'DNK', 'currency' => 'DKK'],
            ['name' => '에스토니아',            'code' => 'EST', 'currency' => 'EUR'],
            ['name' => '핀란드',                'code' => 'FIN', 'currency' => 'EUR'],
            ['name' => '프랑스',                'code' => 'FRA', 'currency' => 'EUR'],
            ['name' => '독일',                  'code' => 'DEU', 'currency' => 'EUR'],
            ['name' => '그리스',                'code' => 'GRC', 'currency' => 'EUR'],
            ['name' => '헝가리',                'code' => 'HUN', 'currency' => 'HUF'],
            ['name' => '아이슬란드',            'code' => 'ISL', 'currency' => 'ISK'],
            ['name' => '아일랜드',              'code' => 'IRL', 'currency' => 'EUR'],
            ['name' => '이탈리아',              'code' => 'ITA', 'currency' => 'EUR'],
            ['name' => '코소보',                'code' => 'XKX', 'currency' => 'EUR'],
            ['name' => '라트비아',              'code' => 'LVA', 'currency' => 'EUR'],
            ['name' => '리히텐슈타인',          'code' => 'LIE', 'currency' => 'CHF'],
            ['name' => '리투아니아',            'code' => 'LTU', 'currency' => 'EUR'],
            ['name' => '룩셈부르크',            'code' => 'LUX', 'currency' => 'EUR'],
            ['name' => '몰타',                  'code' => 'MLT', 'currency' => 'EUR'],
            ['name' => '몰도바',                'code' => 'MDA', 'currency' => 'MDL'],
            ['name' => '모나코',                'code' => 'MCO', 'currency' => 'EUR'],
            ['name' => '몬테네그로',            'code' => 'MNE', 'currency' => 'EUR'],
            ['name' => '네덜란드',              'code' => 'NLD', 'currency' => 'EUR'],
            ['name' => '북마케도니아',          'code' => 'MKD', 'currency' => 'MKD'],
            ['name' => '노르웨이',              'code' => 'NOR', 'currency' => 'NOK'],
            ['name' => '폴란드',                'code' => 'POL', 'currency' => 'PLN'],
            ['name' => '포르투갈',              'code' => 'PRT', 'currency' => 'EUR'],
            ['name' => '루마니아',              'code' => 'ROU', 'currency' => 'RON'],
            ['name' => '러시아',                'code' => 'RUS', 'currency' => 'RUB'],
            ['name' => '산마리노',              'code' => 'SMR', 'currency' => 'EUR'],
            ['name' => '세르비아',              'code' => 'SRB', 'currency' => 'RSD'],
            ['name' => '슬로바키아',            'code' => 'SVK', 'currency' => 'EUR'],
            ['name' => '슬로베니아',            'code' => 'SVN', 'currency' => 'EUR'],
            ['name' => '스페인',                'code' => 'ESP', 'currency' => 'EUR'],
            ['name' => '스웨덴',                'code' => 'SWE', 'currency' => 'SEK'],
            ['name' => '스위스',                'code' => 'CHE', 'currency' => 'CHF'],
            ['name' => '우크라이나',            'code' => 'UKR', 'currency' => 'UAH'],
            ['name' => '영국',                  'code' => 'GBR', 'currency' => 'GBP'],
            ['name' => '바티칸',                'code' => 'VAT', 'currency' => 'EUR'],

            // ===== Oceania =====
            ['name' => '호주',                  'code' => 'AUS', 'currency' => 'AUD'],
            ['name' => '피지',                  'code' => 'FJI', 'currency' => 'FJD'],
            ['name' => '키리바시',              'code' => 'KIR', 'currency' => 'AUD'],
            ['name' => '마셜제도',              'code' => 'MHL', 'currency' => 'USD'],
            ['name' => '미크로네시아',          'code' => 'FSM', 'currency' => 'USD'],
            ['name' => '나우루',                'code' => 'NRU', 'currency' => 'AUD'],
            ['name' => '뉴질랜드',              'code' => 'NZL', 'currency' => 'NZD'],
            ['name' => '팔라우',                'code' => 'PLW', 'currency' => 'USD'],
            ['name' => '파푸아뉴기니',          'code' => 'PNG', 'currency' => 'PGK'],
            ['name' => '사모아',                'code' => 'WSM', 'currency' => 'WST'],
            ['name' => '솔로몬제도',            'code' => 'SLB', 'currency' => 'SBD'],
            ['name' => '통가',                  'code' => 'TON', 'currency' => 'TOP'],
            ['name' => '투발루',                'code' => 'TUV', 'currency' => 'AUD'],
            ['name' => '바누아투',              'code' => 'VUT', 'currency' => 'VUV'],
        ];
    }
}
